# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\guiScript.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 633)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 301, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 70, 211, 351))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 30, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 141, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 141, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 141, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 270, 141, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(90, 30, 101, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 70, 101, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_3.setGeometry(QtCore.QRect(90, 110, 101, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_4.setGeometry(QtCore.QRect(90, 150, 101, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_5.setGeometry(QtCore.QRect(90, 190, 101, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_6.setGeometry(QtCore.QRect(90, 230, 101, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_7.setGeometry(QtCore.QRect(90, 270, 101, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_127 = QtWidgets.QLabel(self.groupBox_3)
        self.label_127.setGeometry(QtCore.QRect(20, 310, 141, 16))
        self.label_127.setObjectName("label_127")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_8.setGeometry(QtCore.QRect(90, 310, 101, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.dial = QtWidgets.QDial(self.tab)
        self.dial.setGeometry(QtCore.QRect(30, 220, 81, 81))
        self.dial.setMaximum(359)
        self.dial.setWrapping(True)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(30, 480, 111, 22))
        self.horizontalSlider_2.setMinimum(-180)
        self.horizontalSlider_2.setMaximum(180)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalSlider = QtWidgets.QSlider(self.tab)
        self.verticalSlider.setGeometry(QtCore.QRect(70, 340, 22, 101))
        self.verticalSlider.setMinimum(-90)
        self.verticalSlider.setMaximum(90)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber.setGeometry(QtCore.QRect(160, 240, 81, 51))
        self.lcdNumber.setDigitCount(4)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_2.setGeometry(QtCore.QRect(160, 460, 81, 51))
        self.lcdNumber_2.setDigitCount(4)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_3.setGeometry(QtCore.QRect(160, 360, 81, 51))
        self.lcdNumber_3.setDigitCount(4)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 461, 531))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 201, 151))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/8_bno055.svg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 190, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 310, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 440, 47, 13))
        self.label_12.setObjectName("label_12")
        self.groupBox_2.raise_()
        self.dial.raise_()
        self.horizontalSlider_2.raise_()
        self.verticalSlider.raise_()
        self.lcdNumber.raise_()
        self.lcdNumber_2.raise_()
        self.lcdNumber_3.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 461, 531))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(20, 30, 191, 151))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/9_vl53l0x.svg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber_4.setGeometry(QtCore.QRect(160, 210, 81, 51))
        self.lcdNumber_4.setDigitCount(4)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_4)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 230, 131, 22))
        self.horizontalSlider.setMinimum(30)
        self.horizontalSlider.setMaximum(1200)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(20, 200, 81, 16))
        self.label_22.setObjectName("label_22")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 471, 531))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(20, 190, 101, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(20, 230, 101, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(20, 270, 101, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(20, 310, 101, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(20, 350, 101, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(20, 390, 101, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(20, 430, 101, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(20, 470, 101, 16))
        self.label_21.setObjectName("label_21")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 121, 171))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/13_multichannelgas.svg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.horizontalSlider_12 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_12.setGeometry(QtCore.QRect(20, 490, 151, 22))
        self.horizontalSlider_12.setMinimum(10)
        self.horizontalSlider_12.setMaximum(500)
        self.horizontalSlider_12.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_12.setObjectName("horizontalSlider_12")
        self.horizontalSlider_11 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_11.setGeometry(QtCore.QRect(20, 450, 151, 22))
        self.horizontalSlider_11.setMinimum(1)
        self.horizontalSlider_11.setMaximum(2000)
        self.horizontalSlider_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_11.setObjectName("horizontalSlider_11")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(20, 250, 151, 22))
        self.horizontalSlider_6.setMaximum(10)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalSlider_9 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_9.setGeometry(QtCore.QRect(20, 370, 151, 22))
        self.horizontalSlider_9.setMinimum(1)
        self.horizontalSlider_9.setMaximum(2000)
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName("horizontalSlider_9")
        self.horizontalSlider_10 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_10.setGeometry(QtCore.QRect(20, 410, 151, 22))
        self.horizontalSlider_10.setMinimum(1)
        self.horizontalSlider_10.setMaximum(2000)
        self.horizontalSlider_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_10.setObjectName("horizontalSlider_10")
        self.horizontalSlider_7 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(20, 290, 151, 22))
        self.horizontalSlider_7.setMinimum(1)
        self.horizontalSlider_7.setMaximum(1000)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.horizontalSlider_8 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(20, 330, 151, 22))
        self.horizontalSlider_8.setMinimum(1)
        self.horizontalSlider_8.setMaximum(500)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(20, 210, 151, 22))
        self.horizontalSlider_3.setMinimum(1)
        self.horizontalSlider_3.setMaximum(1000)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_5.setGeometry(QtCore.QRect(190, 200, 61, 41))
        self.lcdNumber_5.setDigitCount(4)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_8.setGeometry(QtCore.QRect(190, 240, 61, 41))
        self.lcdNumber_8.setDigitCount(4)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_9.setGeometry(QtCore.QRect(190, 280, 61, 41))
        self.lcdNumber_9.setDigitCount(4)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_19 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_19.setGeometry(QtCore.QRect(190, 320, 61, 41))
        self.lcdNumber_19.setDigitCount(4)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.lcdNumber_20 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_20.setGeometry(QtCore.QRect(190, 360, 61, 41))
        self.lcdNumber_20.setDigitCount(4)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.lcdNumber_21 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_21.setGeometry(QtCore.QRect(190, 400, 61, 41))
        self.lcdNumber_21.setDigitCount(4)
        self.lcdNumber_21.setObjectName("lcdNumber_21")
        self.lcdNumber_22 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_22.setGeometry(QtCore.QRect(190, 440, 61, 41))
        self.lcdNumber_22.setDigitCount(4)
        self.lcdNumber_22.setObjectName("lcdNumber_22")
        self.lcdNumber_23 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_23.setGeometry(QtCore.QRect(190, 480, 61, 41))
        self.lcdNumber_23.setDigitCount(4)
        self.lcdNumber_23.setObjectName("lcdNumber_23")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 461, 531))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(10, 40, 191, 81))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/23_pulse.svg"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(20, 200, 51, 16))
        self.label_24.setObjectName("label_24")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.groupBox_6)
        self.lcdNumber_6.setGeometry(QtCore.QRect(160, 210, 81, 51))
        self.lcdNumber_6.setDigitCount(4)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.groupBox_6)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(20, 230, 131, 22))
        self.horizontalSlider_4.setMinimum(30)
        self.horizontalSlider_4.setMaximum(200)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 471, 531))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_27 = QtWidgets.QLabel(self.groupBox_7)
        self.label_27.setGeometry(QtCore.QRect(10, 40, 211, 101))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/27_emg.svg"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setGeometry(QtCore.QRect(20, 200, 121, 16))
        self.label_28.setObjectName("label_28")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.groupBox_7)
        self.lcdNumber_7.setGeometry(QtCore.QRect(160, 210, 81, 51))
        self.lcdNumber_7.setDigitCount(4)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.groupBox_7)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(20, 230, 131, 22))
        self.horizontalSlider_5.setMaximum(255)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_86 = QtWidgets.QLabel(self.tab_6)
        self.label_86.setGeometry(QtCore.QRect(20, 40, 141, 131))
        self.label_86.setText("")
        self.label_86.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/86_thermal.svg"))
        self.label_86.setScaledContents(True)
        self.label_86.setObjectName("label_86")
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_24.setGeometry(QtCore.QRect(10, 10, 471, 531))
        self.groupBox_24.setObjectName("groupBox_24")
        self.horizontalSlider_14 = QtWidgets.QSlider(self.groupBox_24)
        self.horizontalSlider_14.setGeometry(QtCore.QRect(20, 230, 131, 22))
        self.horizontalSlider_14.setMaximum(80)
        self.horizontalSlider_14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_14.setObjectName("horizontalSlider_14")
        self.label_26 = QtWidgets.QLabel(self.groupBox_24)
        self.label_26.setGeometry(QtCore.QRect(20, 200, 111, 16))
        self.label_26.setObjectName("label_26")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.groupBox_24)
        self.lcdNumber_11.setGeometry(QtCore.QRect(160, 210, 81, 51))
        self.lcdNumber_11.setDigitCount(4)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.groupBox_24.raise_()
        self.label_86.raise_()
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_25 = QtWidgets.QLabel(self.tab_7)
        self.label_25.setGeometry(QtCore.QRect(50, 40, 51, 161))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/25_fsr.svg"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_25.setGeometry(QtCore.QRect(10, 10, 471, 531))
        self.groupBox_25.setObjectName("groupBox_25")
        self.label_29 = QtWidgets.QLabel(self.groupBox_25)
        self.label_29.setGeometry(QtCore.QRect(20, 200, 131, 16))
        self.label_29.setObjectName("label_29")
        self.horizontalSlider_13 = QtWidgets.QSlider(self.groupBox_25)
        self.horizontalSlider_13.setGeometry(QtCore.QRect(30, 240, 131, 22))
        self.horizontalSlider_13.setMaximum(255)
        self.horizontalSlider_13.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_13.setObjectName("horizontalSlider_13")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.groupBox_25)
        self.lcdNumber_10.setGeometry(QtCore.QRect(170, 220, 81, 51))
        self.lcdNumber_10.setDigitCount(4)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.groupBox_25.raise_()
        self.label_25.raise_()
        self.tabWidget.addTab(self.tab_7, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(310, 0, 621, 581))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.frame = QtWidgets.QFrame(self.tab_9)
        self.frame.setGeometry(QtCore.QRect(0, 0, 611, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_128 = QtWidgets.QLabel(self.frame)
        self.label_128.setEnabled(True)
        self.label_128.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_128.setText("")
        self.label_128.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/128_emulator2_wiring.svg"))
        self.label_128.setScaledContents(True)
        self.label_128.setObjectName("label_128")
        self.label_129 = QtWidgets.QLabel(self.frame)
        self.label_129.setEnabled(True)
        self.label_129.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_129.setText("")
        self.label_129.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/129_emulator2_red_led.svg"))
        self.label_129.setScaledContents(True)
        self.label_129.setObjectName("label_129")
        self.label_130 = QtWidgets.QLabel(self.frame)
        self.label_130.setEnabled(True)
        self.label_130.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_130.setText("")
        self.label_130.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/130_emulator2_orange_led.svg"))
        self.label_130.setScaledContents(True)
        self.label_130.setObjectName("label_130")
        self.label_131 = QtWidgets.QLabel(self.frame)
        self.label_131.setEnabled(True)
        self.label_131.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_131.setText("")
        self.label_131.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/131_emulator2_yellow_led.svg"))
        self.label_131.setScaledContents(True)
        self.label_131.setObjectName("label_131")
        self.label_132 = QtWidgets.QLabel(self.frame)
        self.label_132.setEnabled(True)
        self.label_132.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_132.setText("")
        self.label_132.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/132_emulator2_green_led.svg"))
        self.label_132.setScaledContents(True)
        self.label_132.setObjectName("label_132")
        self.label_133 = QtWidgets.QLabel(self.frame)
        self.label_133.setEnabled(True)
        self.label_133.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_133.setText("")
        self.label_133.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/133_emulator2_blue_led.svg"))
        self.label_133.setScaledContents(True)
        self.label_133.setObjectName("label_133")
        self.label_134 = QtWidgets.QLabel(self.frame)
        self.label_134.setEnabled(True)
        self.label_134.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_134.setText("")
        self.label_134.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/134_emulator2_top_button.svg"))
        self.label_134.setScaledContents(True)
        self.label_134.setObjectName("label_134")
        self.label_135 = QtWidgets.QLabel(self.frame)
        self.label_135.setEnabled(True)
        self.label_135.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_135.setText("")
        self.label_135.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/135_emulator2_bottom_button.svg"))
        self.label_135.setScaledContents(True)
        self.label_135.setObjectName("label_135")
        self.label_136 = QtWidgets.QLabel(self.frame)
        self.label_136.setEnabled(True)
        self.label_136.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_136.setText("")
        self.label_136.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/136_emulator2_bno055.svg"))
        self.label_136.setScaledContents(True)
        self.label_136.setObjectName("label_136")
        self.label_137 = QtWidgets.QLabel(self.frame)
        self.label_137.setEnabled(True)
        self.label_137.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_137.setText("")
        self.label_137.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/137_emulator2_vl53l0x.svg"))
        self.label_137.setScaledContents(True)
        self.label_137.setObjectName("label_137")
        self.label_138 = QtWidgets.QLabel(self.frame)
        self.label_138.setEnabled(True)
        self.label_138.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_138.setText("")
        self.label_138.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/138_emulator2_gas.svg"))
        self.label_138.setScaledContents(True)
        self.label_138.setObjectName("label_138")
        self.label_139 = QtWidgets.QLabel(self.frame)
        self.label_139.setEnabled(True)
        self.label_139.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_139.setText("")
        self.label_139.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/139_emulator2_pulse.svg"))
        self.label_139.setScaledContents(True)
        self.label_139.setObjectName("label_139")
        self.label_140 = QtWidgets.QLabel(self.frame)
        self.label_140.setEnabled(True)
        self.label_140.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_140.setText("")
        self.label_140.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/140_emulator2_emg.svg"))
        self.label_140.setScaledContents(True)
        self.label_140.setObjectName("label_140")
        self.label_141 = QtWidgets.QLabel(self.frame)
        self.label_141.setEnabled(True)
        self.label_141.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_141.setText("")
        self.label_141.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/141_emulator2_amg8833.svg"))
        self.label_141.setScaledContents(True)
        self.label_141.setObjectName("label_141")
        self.label_142 = QtWidgets.QLabel(self.frame)
        self.label_142.setEnabled(True)
        self.label_142.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_142.setText("")
        self.label_142.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/142_emulator2_fsr.svg"))
        self.label_142.setScaledContents(True)
        self.label_142.setObjectName("label_142")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(310, 460, 211, 71))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_13 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_13.setGeometry(QtCore.QRect(10, 30, 191, 31))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_2.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget_13)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_2.addWidget(self.pushButton_17)
        self.label_143 = QtWidgets.QLabel(self.frame)
        self.label_143.setEnabled(True)
        self.label_143.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_143.setText("")
        self.label_143.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/143_emulator2_buzzer.svg"))
        self.label_143.setScaledContents(True)
        self.label_143.setObjectName("label_143")
        self.label_144 = QtWidgets.QLabel(self.frame)
        self.label_144.setEnabled(True)
        self.label_144.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_144.setText("")
        self.label_144.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/144_emulator2_redled2.svg"))
        self.label_144.setScaledContents(True)
        self.label_144.setObjectName("label_144")
        self.label_145 = QtWidgets.QLabel(self.frame)
        self.label_145.setEnabled(True)
        self.label_145.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_145.setText("")
        self.label_145.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/145_emulator2_motor.svg"))
        self.label_145.setScaledContents(True)
        self.label_145.setObjectName("label_145")
        self.label_146 = QtWidgets.QLabel(self.frame)
        self.label_146.setEnabled(True)
        self.label_146.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_146.setText("")
        self.label_146.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/146_emulator2_buzzer_ON.svg"))
        self.label_146.setScaledContents(True)
        self.label_146.setObjectName("label_146")
        self.label_147 = QtWidgets.QLabel(self.frame)
        self.label_147.setEnabled(True)
        self.label_147.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_147.setText("")
        self.label_147.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/147_emulator2_red_led_ON.svg"))
        self.label_147.setScaledContents(True)
        self.label_147.setObjectName("label_147")
        self.label_148 = QtWidgets.QLabel(self.frame)
        self.label_148.setEnabled(True)
        self.label_148.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_148.setText("")
        self.label_148.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/148_emulator2_orange_led_ON.svg"))
        self.label_148.setScaledContents(True)
        self.label_148.setObjectName("label_148")
        self.label_149 = QtWidgets.QLabel(self.frame)
        self.label_149.setEnabled(True)
        self.label_149.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_149.setText("")
        self.label_149.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/149_emulator2_redled2_ON.svg"))
        self.label_149.setScaledContents(True)
        self.label_149.setObjectName("label_149")
        self.label_150 = QtWidgets.QLabel(self.frame)
        self.label_150.setEnabled(True)
        self.label_150.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_150.setText("")
        self.label_150.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/150_emulator2_yellow_led_ON.svg"))
        self.label_150.setScaledContents(True)
        self.label_150.setObjectName("label_150")
        self.label_151 = QtWidgets.QLabel(self.frame)
        self.label_151.setEnabled(True)
        self.label_151.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_151.setText("")
        self.label_151.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/151_emulator2_green_led_ON.svg"))
        self.label_151.setScaledContents(True)
        self.label_151.setObjectName("label_151")
        self.label_152 = QtWidgets.QLabel(self.frame)
        self.label_152.setEnabled(True)
        self.label_152.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_152.setText("")
        self.label_152.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/152_emulator2_blue_led_ON.svg"))
        self.label_152.setScaledContents(True)
        self.label_152.setObjectName("label_152")
        self.label_153 = QtWidgets.QLabel(self.frame)
        self.label_153.setEnabled(True)
        self.label_153.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_153.setText("")
        self.label_153.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/153_emulator2_motor_BACKWARD.svg"))
        self.label_153.setScaledContents(True)
        self.label_153.setObjectName("label_153")
        self.label_154 = QtWidgets.QLabel(self.frame)
        self.label_154.setEnabled(True)
        self.label_154.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_154.setText("")
        self.label_154.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/154_emulator2_motor_FORWARD.svg"))
        self.label_154.setScaledContents(True)
        self.label_154.setObjectName("label_154")
        self.groupBox_40 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_40.setGeometry(QtCore.QRect(130, 460, 161, 71))
        self.groupBox_40.setObjectName("groupBox_40")
        self.layoutWidget_15 = QtWidgets.QWidget(self.groupBox_40)
        self.layoutWidget_15.setGeometry(QtCore.QRect(10, 30, 141, 23))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_15)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar_16 = QtWidgets.QProgressBar(self.layoutWidget_15)
        self.progressBar_16.setAcceptDrops(True)
        self.progressBar_16.setAutoFillBackground(False)
        self.progressBar_16.setStyleSheet("QProgressBar::chunk{\n"
"    background-color: rgb(231, 12, 4);\n"
"}")
        self.progressBar_16.setMaximum(1)
        self.progressBar_16.setProperty("value", 0)
        self.progressBar_16.setTextVisible(False)
        self.progressBar_16.setObjectName("progressBar_16")
        self.horizontalLayout.addWidget(self.progressBar_16)
        self.progressBar_17 = QtWidgets.QProgressBar(self.layoutWidget_15)
        self.progressBar_17.setStyleSheet("QProgressBar::chunk{\n"
"    \n"
"    background-color: rgb(255, 170, 0);\n"
"}")
        self.progressBar_17.setMaximum(1)
        self.progressBar_17.setProperty("value", 0)
        self.progressBar_17.setTextVisible(False)
        self.progressBar_17.setObjectName("progressBar_17")
        self.horizontalLayout.addWidget(self.progressBar_17)
        self.progressBar_18 = QtWidgets.QProgressBar(self.layoutWidget_15)
        self.progressBar_18.setStyleSheet("QProgressBar::chunk{\n"
"    \n"
"    background-color: rgb(255, 255, 0);\n"
"}")
        self.progressBar_18.setMaximum(1)
        self.progressBar_18.setProperty("value", 0)
        self.progressBar_18.setTextVisible(False)
        self.progressBar_18.setObjectName("progressBar_18")
        self.horizontalLayout.addWidget(self.progressBar_18)
        self.progressBar_19 = QtWidgets.QProgressBar(self.layoutWidget_15)
        self.progressBar_19.setStyleSheet("QProgressBar::chunk{\n"
"    \n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.progressBar_19.setMaximum(1)
        self.progressBar_19.setProperty("value", 0)
        self.progressBar_19.setTextVisible(False)
        self.progressBar_19.setObjectName("progressBar_19")
        self.horizontalLayout.addWidget(self.progressBar_19)
        self.progressBar_20 = QtWidgets.QProgressBar(self.layoutWidget_15)
        self.progressBar_20.setStyleSheet("QProgressBar::chunk{\n"
"    \n"
"    background-color: rgb(14, 203, 255);\n"
"}")
        self.progressBar_20.setMaximum(1)
        self.progressBar_20.setProperty("value", 0)
        self.progressBar_20.setTextVisible(False)
        self.progressBar_20.setObjectName("progressBar_20")
        self.horizontalLayout.addWidget(self.progressBar_20)
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(500, 10, 81, 16))
        self.label_31.setObjectName("label_31")
        self.label_155 = QtWidgets.QLabel(self.frame)
        self.label_155.setEnabled(True)
        self.label_155.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_155.setText("")
        self.label_155.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/155_emulator2_top_button_PRESSED.svg"))
        self.label_155.setScaledContents(True)
        self.label_155.setObjectName("label_155")
        self.label_156 = QtWidgets.QLabel(self.frame)
        self.label_156.setEnabled(True)
        self.label_156.setGeometry(QtCore.QRect(-120, 0, 721, 571))
        self.label_156.setText("")
        self.label_156.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/156_emulator2_bottom_button_PRESSED.svg"))
        self.label_156.setScaledContents(True)
        self.label_156.setObjectName("label_156")
        self.label_128.raise_()
        self.label_129.raise_()
        self.label_130.raise_()
        self.label_131.raise_()
        self.label_132.raise_()
        self.label_134.raise_()
        self.label_135.raise_()
        self.label_144.raise_()
        self.label_147.raise_()
        self.label_148.raise_()
        self.label_149.raise_()
        self.label_150.raise_()
        self.label_151.raise_()
        self.label_31.raise_()
        self.label_155.raise_()
        self.label_156.raise_()
        self.label_146.raise_()
        self.label_143.raise_()
        self.label_152.raise_()
        self.label_133.raise_()
        self.label_145.raise_()
        self.label_153.raise_()
        self.label_154.raise_()
        self.label_136.raise_()
        self.label_137.raise_()
        self.label_138.raise_()
        self.label_139.raise_()
        self.label_140.raise_()
        self.label_141.raise_()
        self.label_142.raise_()
        self.groupBox_40.raise_()
        self.groupBox.raise_()
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_30 = QtWidgets.QLabel(self.tab_10)
        self.label_30.setGeometry(QtCore.QRect(-290, 0, 1001, 691))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("/home/pi/Emulator/.Layers/emulator1_empty.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.tabWidget_2.addTab(self.tab_10, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 21))
        self.menubar.setObjectName("menubar")
        self.menuBNO055 = QtWidgets.QMenu(self.menubar)
        self.menuBNO055.setObjectName("menuBNO055")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuBNO055.addAction(self.actionSave)
        self.menubar.addAction(self.menuBNO055.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.dial.valueChanged['int'].connect(self.lcdNumber.display)
        self.horizontalSlider_6.valueChanged['int'].connect(self.lcdNumber_8.display)
        self.horizontalSlider_6.valueChanged['int'].connect(self.lcdNumber_8.display)
        self.horizontalSlider_10.valueChanged['int'].connect(self.lcdNumber_21.display)
        self.horizontalSlider_11.valueChanged['int'].connect(self.lcdNumber_22.display)
        self.horizontalSlider.valueChanged['int'].connect(self.lcdNumber_4.display)
        self.verticalSlider.valueChanged['int'].connect(self.lcdNumber_3.display)
        self.horizontalSlider_2.valueChanged['int'].connect(self.lcdNumber_2.display)
        self.horizontalSlider_9.valueChanged['int'].connect(self.lcdNumber_20.display)
        self.horizontalSlider_5.valueChanged['int'].connect(self.lcdNumber_7.display)
        self.horizontalSlider_3.valueChanged['int'].connect(self.lcdNumber_5.display)
        self.horizontalSlider_7.valueChanged['int'].connect(self.lcdNumber_9.display)
        self.horizontalSlider_8.valueChanged['int'].connect(self.lcdNumber_19.display)
        self.horizontalSlider_12.valueChanged['int'].connect(self.lcdNumber_23.display)
        self.horizontalSlider_4.valueChanged['int'].connect(self.lcdNumber_6.display)
        self.pushButton_17.pressed.connect(MainWindow.button2_pressed)
        self.pushButton_17.released.connect(MainWindow.button2_released)
        self.pushButton_16.released.connect(MainWindow.button1_released)
        self.pushButton_16.pressed.connect(MainWindow.button1_pressed)
        self.comboBox.currentTextChanged['QString'].connect(MainWindow.update_gpio18)
        self.comboBox_2.currentTextChanged['QString'].connect(MainWindow.update_gpio24)
        self.comboBox_3.currentTextChanged['QString'].connect(MainWindow.update_gpio25)
        self.comboBox_4.currentTextChanged['QString'].connect(MainWindow.update_gpio12)
        self.comboBox_5.currentTextChanged['QString'].connect(MainWindow.update_gpio16)
        self.comboBox_6.currentTextChanged['QString'].connect(MainWindow.update_gpio21)
        self.comboBox_7.currentTextChanged['QString'].connect(MainWindow.update_gpio26)
        self.comboBox_8.currentTextChanged['QString'].connect(MainWindow.update_sensor)
        self.horizontalSlider_13.valueChanged['int'].connect(self.lcdNumber_10.display)
        self.horizontalSlider_14.valueChanged['int'].connect(self.lcdNumber_11.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iBioMed RPi Emulator"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GPIO"))
        self.label.setText(_translate("MainWindow", "GPIO18"))
        self.label_2.setText(_translate("MainWindow", "GPIO24"))
        self.label_3.setText(_translate("MainWindow", "GPIO25"))
        self.label_4.setText(_translate("MainWindow", "GPIO12"))
        self.label_5.setText(_translate("MainWindow", "GPIO16"))
        self.label_6.setText(_translate("MainWindow", "GPIO21"))
        self.label_7.setText(_translate("MainWindow", "GPIO26"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Open"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Red LED"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Buzzer"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Open"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Orange LED"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Red LED"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Open"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Yellow LED"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Open"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Green LED"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Open"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Blue LED"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Motor (GPIO16/20)"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Open"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Push Button"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Open"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Push Button"))
        self.label_127.setText(_translate("MainWindow", "Sensor"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Open"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "Orientation"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "Distance"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "Gas"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "Pulse"))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "EMG"))
        self.comboBox_8.setItemText(6, _translate("MainWindow", "Thermal"))
        self.comboBox_8.setItemText(7, _translate("MainWindow", "FSR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "IO"))
        self.groupBox_2.setTitle(_translate("MainWindow", "BNO055: Orientation Sensor"))
        self.label_10.setText(_translate("MainWindow", "Yaw"))
        self.label_11.setText(_translate("MainWindow", "Pitch"))
        self.label_12.setText(_translate("MainWindow", "Roll"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Orientation"))
        self.groupBox_4.setTitle(_translate("MainWindow", "VL53L0X: Time of Flight Distance Sensor"))
        self.label_22.setText(_translate("MainWindow", "Distance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Distance"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Multichannel Gas Sensor"))
        self.label_14.setText(_translate("MainWindow", "CO"))
        self.label_15.setText(_translate("MainWindow", "NO2"))
        self.label_16.setText(_translate("MainWindow", "H2"))
        self.label_17.setText(_translate("MainWindow", "Ammonia"))
        self.label_18.setText(_translate("MainWindow", "Propane"))
        self.label_19.setText(_translate("MainWindow", "Butane"))
        self.label_20.setText(_translate("MainWindow", "Methane"))
        self.label_21.setText(_translate("MainWindow", "Ethanol"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Gas"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Infrared Pulse Sensor"))
        self.label_24.setText(_translate("MainWindow", "BPM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Pulse"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Myoware EMG"))
        self.label_28.setText(_translate("MainWindow", "Voltage (Digital)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "EMG"))
        self.groupBox_24.setTitle(_translate("MainWindow", "AMG8833 Thermal Array"))
        self.label_26.setText(_translate("MainWindow", "Temperature"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Thermal"))
        self.groupBox_25.setTitle(_translate("MainWindow", "Interlink 402 Force Sensitive Resistor"))
        self.label_29.setText(_translate("MainWindow", "Voltage (Digital)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "FSR"))
        self.groupBox.setTitle(_translate("MainWindow", "Push Buttons"))
        self.pushButton_16.setText(_translate("MainWindow", "Button1"))
        self.pushButton_17.setText(_translate("MainWindow", "Button2"))
        self.groupBox_40.setTitle(_translate("MainWindow", "LEDs"))
        self.label_31.setText(_translate("MainWindow", "(FORWARD)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "RPi"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "T-Cobbler Close-up"))
        self.menuBNO055.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "Coming...soon?"))
